{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "course-tutor.serviceAccountName" . }}
  labels:
    {{- include "course-tutor.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
