"""initial schema

Revision ID: c0ae084fe021
Revises:
Create Date: 2026-08-28 09:43:38.293215
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c0ae084fe021"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Native PG enum types created implicitly by the table definitions below. Listed here
# so downgrade() can drop them; leaving them behind breaks a re-upgrade.
ENUM_TYPES = (
    "access_label",
    "anchor_type",
    "chunk_class",
    "content_version_status",
    "education_level",
    "extraction_status",
    "memory_fact_status",
    "memory_fact_type",
    "user_role",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("dead_lettered_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_outbox_events_idempotency_key")),
    )
    op.create_index("ix_outbox_events_unprocessed", "outbox_events", ["processed_at"], unique=False)
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenants_slug")),
    )
    op.create_table(
        "source_roots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("absolute_path", sa.Text(), nullable=False),
        sa.Column("last_scanned_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_source_roots_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_roots")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("external_subject", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "student", "teaching_assistant", "instructor", "platform_admin", name="user_role"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_users_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("tenant_id", "external_subject", name=op.f("uq_users_tenant_id")),
    )
    op.create_table(
        "courses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "primary",
                "middle_school",
                "high_school",
                "undergraduate",
                "postgraduate",
                name="education_level",
            ),
            nullable=False,
        ),
        sa.Column("active_content_version_id", sa.UUID(), nullable=True),
        sa.Column("source_root_id", sa.UUID(), nullable=True),
        sa.Column("teaching_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["active_content_version_id"],
            ["content_versions.id"],
            name=op.f("fk_courses_active_content_version_id_content_versions"),
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["source_root_id"],
            ["source_roots.id"],
            name=op.f("fk_courses_source_root_id_source_roots"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_courses_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_courses_tenant_id")),
    )
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("rolling_summary", sa.Text(), nullable=True),
        sa.Column("summary_token_count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_chat_sessions_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_chat_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_sessions")),
    )
    op.create_index(
        "ix_chat_sessions_user_course", "chat_sessions", ["user_id", "course_id"], unique=False
    )
    op.create_table(
        "content_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("pipeline_version", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "building",
                "ready",
                "published",
                "failed",
                "rolled_back",
                name="content_version_status",
            ),
            nullable=False,
        ),
        sa.Column("embedding_model_version", sa.String(length=128), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_content_versions_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_versions")),
        sa.UniqueConstraint(
            "course_id", "pipeline_version", "sequence", name=op.f("uq_content_versions_course_id")
        ),
    )
    op.create_table(
        "memory_facts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "learning_goal",
                "knowledge_level",
                "preferred_language_style",
                "stable_constraint",
                "misconception",
                "mastery_signal",
                "active_study_plan",
                name="memory_fact_type",
            ),
            nullable=False,
        ),
        sa.Column("normalized_key", sa.String(length=255), nullable=False),
        sa.Column("normalized_value", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("evidence_turn_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "superseded", "conflicted", "tombstoned", name="memory_fact_status"),
            nullable=False,
        ),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("last_confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("supersedes_id", sa.UUID(), nullable=True),
        sa.Column("tombstoned_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_memory_facts_confidence_range")
        ),
        sa.CheckConstraint(
            "importance >= 0 AND importance <= 1", name=op.f("ck_memory_facts_importance_range")
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_memory_facts_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["memory_facts.id"],
            name=op.f("fk_memory_facts_supersedes_id_memory_facts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_memory_facts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_facts")),
        sa.UniqueConstraint(
            "user_id", "course_id", "type", "normalized_key", name=op.f("uq_memory_facts_user_id")
        ),
    )
    op.create_index(
        "ix_memory_facts_recall", "memory_facts", ["user_id", "course_id", "status"], unique=False
    )
    op.create_table(
        "retrieval_traces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("content_version_id", sa.UUID(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("candidate_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("reranked_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("scores", postgresql.ARRAY(sa.Float()), nullable=False),
        sa.Column("timings_ms", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_version_id"],
            ["content_versions.id"],
            name=op.f("fk_retrieval_traces_content_version_id_content_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_retrieval_traces_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retrieval_traces")),
    )
    op.create_index("ix_retrieval_traces_request", "retrieval_traces", ["request_id"], unique=False)
    op.create_table(
        "source_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "access_label",
            sa.Enum("public", "enrolled", "staff_only", "restricted", name="access_label"),
            nullable=False,
        ),
        sa.Column(
            "extraction_status",
            sa.Enum(
                "pending",
                "extracted",
                "ocr_extracted",
                "quarantined",
                "failed",
                name="extraction_status",
            ),
            nullable=False,
        ),
        sa.Column("extraction_confidence", sa.Float(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("artifact_key", sa.Text(), nullable=True),
        sa.Column("source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "extraction_confidence IS NULL OR (extraction_confidence >= 0 AND extraction_confidence <= 1)",
            name=op.f("ck_source_documents_extraction_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["content_versions.id"],
            name=op.f("fk_source_documents_version_id_content_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
        sa.UniqueConstraint("version_id", "checksum", name="uq_source_documents_version_checksum"),
        sa.UniqueConstraint("version_id", "relative_path", name="uq_source_documents_version_path"),
    )
    op.create_index(
        "ix_source_documents_extraction_status",
        "source_documents",
        ["extraction_status"],
        unique=False,
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column(
            "anchor_type",
            sa.Enum("page", "slide", "heading", "timestamp", "line_range", name="anchor_type"),
            nullable=False,
        ),
        sa.Column("anchor_value", sa.String(length=128), nullable=False),
        sa.Column(
            "chunk_class",
            sa.Enum(
                "content",
                "exercise_question",
                "exercise_solution",
                "assessment",
                name="chunk_class",
            ),
            nullable=False,
        ),
        sa.Column("embedding_model_version", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_documents.id"],
            name=op.f("fk_chunks_source_id_source_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint("source_id", "ordinal", name=op.f("uq_chunks_source_id")),
    )
    op.create_index("ix_chunks_source_class", "chunks", ["source_id", "chunk_class"], unique=False)
    # ### end Alembic commands ###

    # courses.active_content_version_id <-> content_versions.course_id is a cycle, so
    # autogenerate omits it. Add it after both tables exist (use_alter semantics).
    op.create_foreign_key(
        "fk_courses_active_content_version_id_content_versions",
        "courses",
        "content_versions",
        ["active_content_version_id"],
        ["id"],
    )


def downgrade() -> None:
    op.drop_constraint(
        "fk_courses_active_content_version_id_content_versions",
        "courses",
        type_="foreignkey",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chunks_source_class", table_name="chunks")
    op.drop_table("chunks")
    op.drop_index("ix_source_documents_extraction_status", table_name="source_documents")
    op.drop_table("source_documents")
    op.drop_index("ix_retrieval_traces_request", table_name="retrieval_traces")
    op.drop_table("retrieval_traces")
    op.drop_index("ix_memory_facts_recall", table_name="memory_facts")
    op.drop_table("memory_facts")
    op.drop_table("content_versions")
    op.drop_index("ix_chat_sessions_user_course", table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_table("courses")
    op.drop_table("users")
    op.drop_table("source_roots")
    op.drop_table("tenants")
    op.drop_index("ix_outbox_events_unprocessed", table_name="outbox_events")
    op.drop_table("outbox_events")
    # ### end Alembic commands ###

    # Alembic does not emit these: dropping a table leaves its native enum type in
    # place, so a re-upgrade would fail with DuplicateObjectError.
    for enum_name in ENUM_TYPES:
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
